// CoScene — collaborative scene engine for StreamBro.
//
// Purpose: keep S.srcs / S.items synchronised across up to 4 peers in a room
// over the existing WebRTC data-channels with last-writer-wins per item.
//
// Public API (everything reachable from app.js):
//   const co = new CoScene({ getState, applyOp, getMyPeerId, log });
//   co.attach(wrtcManager)        — hook into manager's data channels
//   co.setMyPeerId(peerId)        — when room-created/joined fires
//   co.broadcastOp(op)            — fire-and-forget to all open channels
//   co.queueItemUpsert(it)        — throttled (≈33ms) per-item upsert
//   co.flushItem(sid)             — immediate flush (use on mouseup)
//   co.broadcastSourceAdd(src)    — when local src created
//   co.broadcastSourceRemove(gid) — when local src removed
//   co.broadcastItemRemove(sid)
//   co.broadcastSrcReorder(gids)
//   co.applyingRemote()           — true while a remote op is being applied
//                                   (use to suppress echo broadcasts)
//   co.bindPendingTrack(streamId, fromPid, kind, track)
//                                 — call from wrtc.ontrack to attach track
//   co.lookupGidByMsid(msid)      — for ontrack handler
//
// Protocol (over data channel, JSON):
//   { op:'snapshot',   srcs:[...], items:[...], from:peerId, ts }
//   { op:'src.add',    src:{...}, ts }
//   { op:'src.remove', gid, ts }
//   { op:'src.reorder', order:[gid, gid, ...], ts }      // global ordering
//   { op:'item.upsert', it:{...}, ts }
//   { op:'item.remove', sid, ts }
//   { op:'cursor', x, y, ts }                            // optional, throttled
//   { op:'request-snapshot' }                            // ask for full state
//
// Notes
//   * `gid` is a globally-unique id, generated by source owner — we use
//      `crypto.randomUUID()` (collision probability ~0).
//   * `it.sid` is identical to the owning `src.gid` (1-to-1 binding).
//   * Each op carries a millisecond `ts`. On collision we keep the newer.
//   * The data-channel uses `ordered:true` (already configured in webrtc.js)
//     so per-channel ordering is preserved.
//   * Audio anti-echo: a peer NEVER re-broadcasts a remote source upstream.
//     `src.add` for an `ownerPeerId !== myPeerId` is replicated only to other
//     peers via reflective forwarding (mesh-relay) when explicitly requested.
//     For an MVP mesh of ≤4 peers every member is connected to every other,
//     so authoritative ops always come from the owner directly — no relay
//     needed and no echo possible.

(function(){
  'use strict';

  const PROTO_VERSION = 1;
  const ITEM_UPSERT_HZ = 30;          // throttle rate for drag/resize updates
  const ITEM_UPSERT_INTERVAL = 1000 / ITEM_UPSERT_HZ;
  const CURSOR_HZ = 20;
  const CURSOR_INTERVAL = 1000 / CURSOR_HZ;

  function _nowTs() { return Date.now(); }

  // List of fields we replicate for an `it`. Anything not in this list stays
  // local (e.g. `_isPreview`, `prevRect`).
  const ITEM_FIELDS = [
    'sid','cx','cy','w','h','z','rot','flipH','flipV',
    'crop','cropMask','frameSettings',
    'uncropW','uncropH','uncropCx','uncropCy',
    'origVW','origVH','naturalAR',
    'panDx','panDy',
  ];

  // Source fields we replicate. We deliberately DO NOT replicate `stream`,
  // `el`, audio-context bindings, and other binary/local-only refs.
  const SRC_FIELDS = [
    'gid','ownerPeerId','type','name','isPeer','peerId',
    'visible','locked','vol','muted','monitor','channelMode','msid',
    'camSettings','fxState',
  ];

  function pickFields(obj, fields) {
    if (!obj) return null;
    const out = {};
    for (const f of fields) {
      if (obj[f] !== undefined) out[f] = obj[f];
    }
    return out;
  }

  // Deep clone of plain JSON-safe data (no refs to MediaStream / Element)
  function cloneJSON(v) { try { return JSON.parse(JSON.stringify(v)); } catch (_) { return null; } }

  class CoScene {
    constructor(opts) {
      opts = opts || {};
      this.handlers = opts.handlers || {};
      this.log = opts.log || function(){};
      this.myPeerId = null;

      this.wrtc = null;
      this._channels = new Map(); // peerId -> RTCDataChannel
      this._applyingRemote = false;

      // Throttle bookkeeping: per-sid last-sent-at and pending payload
      this._itemPending = new Map(); // sid -> {it, scheduledAt}
      this._itemTimer = null;

      // Cursor throttle
      this._cursorPending = null;
      this._cursorTimer = null;

      // Track binding: maps received before the matching `src.add` arrived,
      // and src.adds received before tracks. MVP keys by stream.id (msid).
      this._pendingTracksByMsid = new Map(); // msid -> [{stream, kind, peerId}]
      this._pendingSrcByMsid = new Map();    // msid -> srcMeta

      // For LWW
      this._lastSeenTs = new Map(); // sid|gid -> ts

      // Snapshot send debounce after channel open
      this._snapshotSendTimers = new Map();
    }

    setMyPeerId(pid) { this.myPeerId = pid; }

    setHandlers(h) { this.handlers = h || {}; }

    applyingRemote() { return this._applyingRemote; }

    // ─── Data-channel plumbing ───────────────────────────────────────────────

    attachChannel(peerId, dc) {
      if (!dc) return;
      this._channels.set(peerId, dc);
      const onMsg = (e) => {
        let msg;
        try { msg = JSON.parse(e.data); } catch { return; }
        if (!msg || !msg.op) return;
        this._dispatch(peerId, msg);
      };
      dc.addEventListener('message', onMsg);
      const onOpen = () => {
        this.log('[CoScene] dc open ←→', peerId);
        // Send snapshot once after a small delay to let app side wire up
        clearTimeout(this._snapshotSendTimers.get(peerId));
        this._snapshotSendTimers.set(peerId, setTimeout(() => {
          this._sendSnapshot(peerId);
        }, 200));
      };
      if (dc.readyState === 'open') onOpen();
      else dc.addEventListener('open', onOpen);
      const onClose = () => { this._channels.delete(peerId); };
      dc.addEventListener('close', onClose);
    }

    detachPeer(peerId) {
      this._channels.delete(peerId);
    }

    // ─── Sending ────────────────────────────────────────────────────────────

    _sendTo(peerId, obj) {
      const dc = this._channels.get(peerId);
      if (!dc || dc.readyState !== 'open') return false;
      try { dc.send(JSON.stringify(obj)); return true; } catch (_) { return false; }
    }

    broadcast(obj) {
      if (!obj) return;
      for (const [pid, dc] of this._channels) {
        if (dc.readyState === 'open') {
          try { dc.send(JSON.stringify(obj)); } catch (_) {}
        }
      }
    }

    broadcastOp(op) { this.broadcast(op); }

    // ─── High-level helpers ─────────────────────────────────────────────────

    broadcastSourceAdd(src) {
      if (this._applyingRemote) return;
      const meta = pickFields(src, SRC_FIELDS);
      if (!meta || !meta.gid) return;
      this.broadcast({ op:'src.add', src: meta, ts: _nowTs() });
    }

    broadcastSourceRemove(gid) {
      if (this._applyingRemote) return;
      this.broadcast({ op:'src.remove', gid, ts: _nowTs() });
    }

    broadcastSourceUpdate(src) {
      // Same payload format as src.add but signals "patch existing".
      // Audio/visual settings only — no MediaStream bindings touched.
      if (this._applyingRemote) return;
      const meta = pickFields(src, SRC_FIELDS);
      if (!meta || !meta.gid) return;
      this.broadcast({ op:'src.update', src: meta, ts: _nowTs() });
    }

    broadcastItemRemove(sid) {
      if (this._applyingRemote) return;
      this.broadcast({ op:'item.remove', sid, ts: _nowTs() });
    }

    broadcastSrcReorder(orderGids) {
      if (this._applyingRemote) return;
      this.broadcast({ op:'src.reorder', order: orderGids, ts: _nowTs() });
    }

    queueItemUpsert(it) {
      if (this._applyingRemote || !it || !it.sid) return;
      const safe = pickFields(it, ITEM_FIELDS);
      if (!safe) return;
      // Mark our timestamp now — receiver uses LWW
      this._itemPending.set(it.sid, safe);
      if (this._itemTimer) return;
      this._itemTimer = setTimeout(() => this._flushItemQueue(), ITEM_UPSERT_INTERVAL);
    }

    flushItem(sid) {
      const it = this._itemPending.get(sid);
      if (it) {
        this.broadcast({ op:'item.upsert', it: cloneJSON(it), ts: _nowTs() });
        this._itemPending.delete(sid);
      }
    }

    flushAllItems() {
      for (const [sid, it] of this._itemPending) {
        this.broadcast({ op:'item.upsert', it: cloneJSON(it), ts: _nowTs() });
      }
      this._itemPending.clear();
    }

    _flushItemQueue() {
      this._itemTimer = null;
      if (!this._itemPending.size) return;
      const ts = _nowTs();
      for (const [sid, it] of this._itemPending) {
        this.broadcast({ op:'item.upsert', it: cloneJSON(it), ts });
      }
      this._itemPending.clear();
    }

    queueCursor(x, y) {
      if (this._applyingRemote) return;
      this._cursorPending = { x, y };
      if (this._cursorTimer) return;
      this._cursorTimer = setTimeout(() => {
        this._cursorTimer = null;
        const c = this._cursorPending;
        this._cursorPending = null;
        if (c) this.broadcast({ op:'cursor', x: c.x, y: c.y, ts: _nowTs() });
      }, CURSOR_INTERVAL);
    }

    _sendSnapshot(peerId) {
      const h = this.handlers || {};
      if (!h.getSnapshot) return;
      const snap = h.getSnapshot();
      if (!snap) return;
      const out = {
        op: 'snapshot',
        v: PROTO_VERSION,
        from: this.myPeerId || null,
        srcs: (snap.srcs || []).map(s => pickFields(s, SRC_FIELDS)).filter(Boolean),
        items: (snap.items || []).map(i => pickFields(i, ITEM_FIELDS)).filter(Boolean),
        order: (snap.order || []),
        ts: _nowTs(),
      };
      this._sendTo(peerId, out);
    }

    requestSnapshotFromAll() {
      this.broadcast({ op:'request-snapshot', ts: _nowTs() });
    }

    // ─── Receiving ──────────────────────────────────────────────────────────

    _dispatch(fromPid, msg) {
      const h = this.handlers || {};
      this._applyingRemote = true;
      try {
        switch (msg.op) {
          case 'snapshot':       this._applySnapshot(fromPid, msg); break;
          case 'src.add':        this._applySrcAdd(fromPid, msg.src, msg.ts); break;
          case 'src.update':     this._applySrcUpdate(fromPid, msg.src, msg.ts); break;
          case 'src.remove':     this._applySrcRemove(fromPid, msg.gid, msg.ts); break;
          case 'src.reorder':    if (h.applySrcReorder) h.applySrcReorder(msg.order || []); break;
          case 'item.upsert':    this._applyItemUpsert(fromPid, msg.it, msg.ts); break;
          case 'item.remove':    if (h.applyItemRemove) h.applyItemRemove(msg.sid); break;
          case 'cursor':         if (h.applyCursor) h.applyCursor(fromPid, msg.x, msg.y); break;
          case 'request-snapshot': this._sendSnapshot(fromPid); break;
        }
      } catch (e) {
        this.log('[CoScene] dispatch error:', msg.op, e);
      }
      this._applyingRemote = false;
    }

    _applySnapshot(fromPid, msg) {
      const h = this.handlers || {};
      // Apply each source via the same path as src.add (LWW guards collisions)
      if (Array.isArray(msg.srcs)) {
        for (const s of msg.srcs) this._applySrcAdd(fromPid, s, msg.ts);
      }
      if (Array.isArray(msg.items)) {
        for (const it of msg.items) this._applyItemUpsert(fromPid, it, msg.ts);
      }
      if (Array.isArray(msg.order) && msg.order.length && h.applySrcReorder) {
        h.applySrcReorder(msg.order);
      }
    }

    _applySrcAdd(fromPid, srcMeta, ts) {
      const h = this.handlers || {};
      if (!srcMeta || !srcMeta.gid) return;
      if (!h.applySrcAdd) return;
      const prev = this._lastSeenTs.get('src:' + srcMeta.gid) || 0;
      if (ts && ts < prev) return;            // older — ignore
      this._lastSeenTs.set('src:' + srcMeta.gid, ts || _nowTs());

      // If a media track already arrived for this msid, hand it off
      let pending = null;
      if (srcMeta.msid && this._pendingTracksByMsid.has(srcMeta.msid)) {
        pending = this._pendingTracksByMsid.get(srcMeta.msid);
        this._pendingTracksByMsid.delete(srcMeta.msid);
      }
      h.applySrcAdd(srcMeta, pending, fromPid);

      // Otherwise stash for later when ontrack fires
      if (srcMeta.msid && !pending) {
        this._pendingSrcByMsid.set(srcMeta.msid, { srcMeta, fromPid });
      }
    }

    _applySrcUpdate(fromPid, srcMeta, ts) {
      const h = this.handlers || {};
      if (!srcMeta || !srcMeta.gid) return;
      const key = 'src.upd:' + srcMeta.gid;
      const prev = this._lastSeenTs.get(key) || 0;
      if (ts && ts < prev) return;
      this._lastSeenTs.set(key, ts || _nowTs());
      if (h.applySrcUpdate) h.applySrcUpdate(srcMeta);
    }

    _applySrcRemove(fromPid, gid, ts) {
      const h = this.handlers || {};
      if (!gid) return;
      const prev = this._lastSeenTs.get('src:' + gid) || 0;
      if (ts && ts < prev) return;
      this._lastSeenTs.set('src:' + gid, ts || _nowTs());
      if (h.applySrcRemove) h.applySrcRemove(gid);
    }

    _applyItemUpsert(fromPid, it, ts) {
      const h = this.handlers || {};
      if (!it || !it.sid) return;
      const key = 'item:' + it.sid;
      const prev = this._lastSeenTs.get(key) || 0;
      if (ts && ts < prev) return;
      this._lastSeenTs.set(key, ts || _nowTs());
      if (h.applyItemUpsert) h.applyItemUpsert(it);
    }

    // ─── Track ↔ source binding helpers (used from webrtc.js ontrack) ──────

    // Called by WebRTCManager.onRemoteStream.
    // Returns srcMeta if the matching src.add already arrived, else stashes
    // the stream and returns null.
    bindIncomingStream(stream, kind, peerId) {
      if (!stream) return null;
      const msid = stream.id;
      const pendingSrc = this._pendingSrcByMsid.get(msid);
      if (pendingSrc) {
        this._pendingSrcByMsid.delete(msid);
        return { srcMeta: pendingSrc.srcMeta, fromPid: pendingSrc.fromPid };
      }
      // No matching src.add yet — stash track for later
      const list = this._pendingTracksByMsid.get(msid) || { streams: [] };
      list.streams.push({ stream, kind, peerId });
      list.peerId = peerId;
      this._pendingTracksByMsid.set(msid, list);
      return null;
    }
  }

  // ─── Helpers exposed to app.js ───────────────────────────────────────────

  function newGid() {
    if (window.crypto && window.crypto.randomUUID) return window.crypto.randomUUID();
    // Fallback — collision-resistant enough for one room
    return 'g-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 10);
  }

  window.CoScene = CoScene;
  window.CoSceneHelpers = {
    newGid,
    pickFields,
    cloneJSON,
    SRC_FIELDS,
    ITEM_FIELDS,
    PROTO_VERSION,
    ITEM_UPSERT_HZ,
  };
})();
